// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTranscodeTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function AddTranscodeTaskWithParams(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function CancelDownload(arg1:string):Promise<string>;

export function CancelTranscode(arg1:string):Promise<string>;

export function DownloadTorrentFiles(arg1:string,arg2:Array<string>):Promise<string>;

export function DownloadWithTool(arg1:string,arg2:string):Promise<string>;

export function GenerateMagnetLink(arg1:string):Promise<string>;

export function GetDiskSpace():Promise<string>;

export function GetDownloadStatus(arg1:string):Promise<string>;

export function GetTranscodeStatus(arg1:string):Promise<string>;

export function GetVideoLibrary():Promise<string>;

export function ParseTorrentFile(arg1:string):Promise<string>;

export function ServeVideoFile(arg1:string):Promise<string>;

export function StartTranscode(arg1:string):Promise<string>;

export function StartWaitingTask(arg1:string):Promise<string>;

export function UploadFile(arg1:string):Promise<string>;
