// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTranscodeTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddTranscodeTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddTranscodeTaskWithParams(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddTranscodeTaskWithParams'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CancelTranscode(arg1) {
  return window['go']['main']['App']['CancelTranscode'](arg1);
}

export function DownloadTorrentFiles(arg1, arg2) {
  return window['go']['main']['App']['DownloadTorrentFiles'](arg1, arg2);
}

export function DownloadWithTool(arg1, arg2) {
  return window['go']['main']['App']['DownloadWithTool'](arg1, arg2);
}

export function GenerateMagnetLink(arg1) {
  return window['go']['main']['App']['GenerateMagnetLink'](arg1);
}

export function GetDiskSpace() {
  return window['go']['main']['App']['GetDiskSpace']();
}

export function GetDownloadStatus(arg1) {
  return window['go']['main']['App']['GetDownloadStatus'](arg1);
}

export function GetTranscodeStatus(arg1) {
  return window['go']['main']['App']['GetTranscodeStatus'](arg1);
}

export function GetVideoLibrary() {
  return window['go']['main']['App']['GetVideoLibrary']();
}

export function ParseTorrentFile(arg1) {
  return window['go']['main']['App']['ParseTorrentFile'](arg1);
}

export function ServeVideoFile(arg1) {
  return window['go']['main']['App']['ServeVideoFile'](arg1);
}

export function StartTranscode(arg1) {
  return window['go']['main']['App']['StartTranscode'](arg1);
}

export function StartWaitingTask(arg1) {
  return window['go']['main']['App']['StartWaitingTask'](arg1);
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}
